/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspbo21juni2025;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class pertamina extends javax.swing.JFrame {

    /**
     * Creates new form pertamina
     */
    public pertamina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPertamina = new javax.swing.JLabel();
        labelDo = new javax.swing.JLabel();
        labelSpbu = new javax.swing.JLabel();
        labelBbm = new javax.swing.JLabel();
        labelLiter = new javax.swing.JLabel();
        labelTgl = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        txtDo = new javax.swing.JTextField();
        txtSpbu = new javax.swing.JTextField();
        txtLiter = new javax.swing.JTextField();
        cbBbm = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        txtTgl = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPertamina.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        labelPertamina.setText("FORMULIR DISTRIBUSI BBM PERTAMINA");

        labelDo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelDo.setText("Nomor DO ");

        labelSpbu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelSpbu.setText("Nama SPBU");

        labelBbm.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelBbm.setText("Jenis BBM");

        labelLiter.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelLiter.setText("Jumlah Liter ");

        labelTgl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelTgl.setText("Tanggal pengiriman ");

        labelStatus.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelStatus.setText("Status pengiriman ");

        cbBbm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis BBM", "Pertalite", "Pertamax", "Pertamax Turbo", "Solar", "Dexlite" }));
        cbBbm.setToolTipText("");

        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status Pengiriman", "Menunggu Pengiriman", "Dalam Perjalanan", "Tiba di Lokasi", "Selesai", "Tertunda", "Dibatalkan" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelLiter, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelSpbu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelDo)
                            .addGap(144, 144, 144)))
                    .addComponent(labelStatus)
                    .addComponent(labelTgl)
                    .addComponent(labelBbm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDo, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(txtSpbu)
                        .addComponent(txtLiter)
                        .addComponent(cbBbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTgl))
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(371, 371, 371))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPertamina)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(labelPertamina)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDo)
                    .addComponent(txtDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSpbu)
                    .addComponent(txtSpbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBbm)
                    .addComponent(cbBbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLiter)
                    .addComponent(txtLiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTgl)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
    // Ambil nilai dari setiap komponen form
    String nomorDO = txtDo.getText().trim();
    String namaSpbu = txtSpbu.getText().trim();
    String jenisBbm = cbBbm.getSelectedItem().toString();
    String jumlahLiter = txtLiter.getText().trim();
    String tanggalKirim = txtTgl.getText().trim();
    String statusPengiriman = cbStatus.getSelectedItem().toString();

    if (nomorDO.isEmpty() || namaSpbu.isEmpty() || jumlahLiter.isEmpty() || tanggalKirim.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Semua field harus diisi!", 
            "Validasi Gagal", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Output ke console
    System.out.println("=== Data Distribusi BBM ===");
    System.out.println("Nomor DO: " + nomorDO);
    System.out.println("Nama SPBU: " + namaSpbu);
    System.out.println("Jenis BBM: " + jenisBbm);
    System.out.println("Jumlah Liter: " + jumlahLiter);
    System.out.println("Tanggal Pengiriman: " + tanggalKirim);
    System.out.println("Status Pengiriman: " + statusPengiriman);
    
    JOptionPane.showMessageDialog(this, 
            "Data berhasil disubmit!", 
            "Sukses", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pertamina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pertamina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pertamina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pertamina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new pertamina().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbBbm;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel labelBbm;
    private javax.swing.JLabel labelDo;
    private javax.swing.JLabel labelLiter;
    private javax.swing.JLabel labelPertamina;
    private javax.swing.JLabel labelSpbu;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTgl;
    private javax.swing.JTextField txtDo;
    private javax.swing.JTextField txtLiter;
    private javax.swing.JTextField txtSpbu;
    private javax.swing.JTextField txtTgl;
    // End of variables declaration//GEN-END:variables
}
